version: '3.8'

services:
  # Приложение Ham Radio Diplomas Parser
  app:
    build:
      context: .
      network: host
    container_name: hamlog-parser
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - hamlog-network

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: hamlog-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - hamlog-network

  bot:
    build: ./telegram-bot
    env_file:
      - ./telegram-bot/.env
    networks:
      - hamlog-network
    depends_on:
      - redis

networks:
  hamlog-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
